### PR TITLE
Add message handling wrapper/decorator

### PR DESCRIPTION
**Pull request by mattprintz**
Adds a @message_handler decorator/wrapper to help with custom message handling.

Abstracts some of the message idiosyncrasies and ensures a proper _reply response to every request as specified in the Jupyter documentation.

### CODE REVIEW

**Review by fivegrant — CHANGES_REQUESTED** [review]
I keep getting a module not found error for `lib.utils`. I don't see a `lib/utils.py`. Maybe it needs to be committed?

**Comment by mattprintz** [comment]
@fivegrant Yep. It was just sitting there not added. Pushed it up.

**Review by fivegrant — APPROVED** [review]
It works for me now.

**Comment by fivegrant** [comment]
@mattprintz is this a dead branch?

**Comment by mattprintz** [comment]
@fivegrant Yes it is. Thanks for catching.

**Pull request closed without merging**
